image: ubuntu:22.04

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt-get update || true
  - apt-get -y install curl libhdf5-dev build-essential doxygen
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env

deploy:
  stage: deploy
  tags:
    - flores.docs@docker
  only:
    - main
  script:
    - doxygen doc/Doxyfile
    - UV_CACHE_DIR=".uv-cache" uv run --group doc sphinx-build -b html doc doc/build
    - mkdir -p $DOCS
    - rm -rf $DOCS/*
    - cp -R doc/build/* $DOCS/
