variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - scl enable devtoolset-9 bash
  - source /opt/rh/devtoolset-9/enable
  - module load  anaconda/3 boost/1.73.0 hdf5/1.12.0
  - conda activate h5features-ci
  - mkdir -p build
  - cd build

test-linux:
  stage: test
  script:
    - cmake3 -DH5FEATURES_BUILD_TEST=ON -DH5FEATURES_BUILD_PYTHON=ON ..
    - make -j6
    - make test
  tags:
    - oberon

documentation:
  stage: deploy
  script:
    - cmake3 -DH5FEATURES_BUILD_DOC=ON ..
    - make doc
#     - ssh cognitive-ml.fr "rm -rf /var/www/docs.cognitive-mml.fr/h5features/*"
#     - scp -r doc/html/* cognitive-ml.fr:/var/www/docs.cognitive-ml.fr/h5features
  only:
    refs:
      - master
  tags:
    - oberon
